import 'package:flutter/material.dart';

const Color appColor = Color(0xff6750A4);
const Color skyBlue = Color(0xffEADDFF);
const Color secondaryAppColor = Color(0xff625B71);
const Color greyColor = Colors.grey;
const Color blackColor = Colors.black;
const Color whiteColor = Colors.white;
const Color lightPurple = Color(0xffE8DEF8);
const Color darkBlue = Color(0xff1D192B);
// const Color lightGreyColor = Color(0xffbfbfbf);
// const Color greyColor = Color(0xff6c6e6e);
// const Color greyFontColor = Color(0xff777777);
// const Color texFieldColor = Colors.white;
// const Color drawerColor = Color(0xff273638);
// const Color greenColor = Color(0xff4caf50);
// const Color lightRedColor = Color(0xffffcdd2);
// const Color red100Color = Color(0xfffce4e0);
// const Color red500Color = Color(0xffef9a9a);
// const Color red800Color = Color(0xffe57373);
// const Color snackBarColor = Color(0xffd9534f);
